### ISSUE TITLE
Where did the "Restaurant" type come from

### ISSUE THREAD

**Issue by JetChan-Better** [alxnkt/nuxt3-strapi4#1]
https://github.com/alxnkt/nuxt3-strapi4/blob/0b223de036b45e40623134dfc96844f2184c705e/nuxt3/pages/nuxt-strapi/index.vue#L16

Where did the "Restaurant" type come from

**Comment by alxnkt** [comment]
Hello, @JetChan-Better!
It's from `@nuxtjs/strapi` module for integration with Strapi.
You have to add with following command:
`yarn add --dev @nuxtjs/strapi`

**Comment by tuguldurio** [comment]
I have @nuxtjs/strapi installed. However, I still have no access to the types.

**Comment by danplaton4** [comment]
is anyone having the same issue? I don't have an '~types' folder in my root app after installing @nuxtjs/strapi.

**Comment by alxnkt** [comment]
Hello @danplaton4 @tuguldurio @JetChan-Better 
I should have made this more clear. You have to create `types` folder by yourself and create appropriate types here. 
Now I've updated the repo, added folder `types` and `Restaurant` type. Please, update the code.
![screenshot](https://user-images.githubusercontent.com/49128174/214565325-81553c0a-4376-459f-80dc-b026b63f50ac.png)

**Comment by JetChan-Better** [comment]
Okay, I know how to solve this question
