### ISSUE TITLE
Why do we need to call refresh when the component is mounted?

### ISSUE THREAD

**Issue by samrap** [alxnkt/nuxt3-strapi4#2]
I noticed that without calling `refresh()` from `useAsyncData` that no data is returned. Doesn't this defeat the purpose of SSR?

https://github.com/alxnkt/nuxt3-strapi4/blob/main/nuxt3/pages/fetch/index.vue#LL20C4-L20C4

**Comment by alxnkt** [comment]
Hello, @samrap!
Thank you for your question. In fact, there is no need to use `refresh()` here with `useAsyncData`. Looks like is's some kind of vestige here... `refresh()` makes sense when using  `useLazyAsyncData`, in this case it's useful to use `pending` as well. Now I have updated code to avoid ambiguity and use advantage of SSR:
```html
<template>
  <div>
    <ul>
      <li v-for="restaurant in restaurants.data" :key="restaurant.id">
        {{ restaurant.attributes.name }}
        <button @click="$router.push(`${$route.path}/restaurant/${restaurant.id}`)">Edit</button>
        <button @click="deleteRestaurant(restaurant.id)">Delete</button>
      </li>
    </ul>
    <nuxt-link :to="`${$route.path}/restaurant/create`">Create</nuxt-link>
  </div>
</template>

<script setup>
const { data: restaurants, refresh } = await useAsyncData(
  'restaurants', 
  () => $fetch("http://localhost:1337/api/restaurants")
)

const deleteRestaurant = async (restaurantId) => {
  await $fetch(`http://localhost:1337/api/restaurants/${restaurantId}`, {
    method: 'DELETE'
  })
  refresh()
}
</script>
```

**Comment by samrap** [comment]
Cool, thank you for clarifying!
